### ISSUE TITLE
Question about the evaluation code.

### ISSUE THREAD

**Issue by JacobYuan7** [yoyomimi/AS-Net#15]
Thanks for your great work. There is a question haunting me about the evaluation process. 
The line 139 in _hico_eval.py_ only ensures the human and the object are rightly localized. Why does the TP not consider the object class for a TP?

**Comment by YueLiao** [comment]
Line 90 in hico_eval.py ensures it.

**Comment by JacobYuan7** [comment]
@YueLiao 
Do you mean these two lines of codes? I don't quite get it.
_if res_num == 0:
      continue_

But it does not seem to ensure that the object class is right.

**Comment by YueLiao** [comment]
Sorry, it's Line 190.

**Comment by JacobYuan7** [comment]
@YueLiao  Thank u, it solved my concern.
