### ISSUE TITLE
HOI-A Pretrained model 

### ISSUE THREAD

**Issue by Bo396543018** [yoyomimi/AS-Net#5]
你好呀，请问下有没有HOI-A相关的模型以及脚本呢？
另外关于HOIA数据集里有部分错误标注请问你是怎么处理的呀0.0

**Comment by yoyomimi** [comment]
您好，这几天我会release这部分代码和模型～

**Comment by Bo396543018** [comment]
@yoyomimi 好的 谢谢~

**Comment by yoyomimi** [comment]
> @yoyomimi 好的 谢谢~

您好，hoia部分已经上传完毕，如果遇到新的问题，请反馈给我，感谢～

**Comment by Bo396543018** [comment]
@yoyomimi  十分感谢~ 学习一波哈哈

**Comment by Bo396543018** [comment]
@yoyomimi 你好，关于HOIA的数据集还有个问题想请教下：关于corre_hoia.npy,里面的关系相比PPDM论文table1列举的关系里多了read computer，少了hold computer，请问这个背后的原因是什么呀
