### ISSUE TITLE
a problem with the image shape of the input model

### ISSUE THREAD

**Issue by hutao568** [yoyomimi/AS-Net#7]
Hello Mingfei Chen, everything works normally when I use single GPU for training, but when I use multiple GPUs to train HOIA dataset, I encounter a problem, I would like to ask you how to solve it,there is a problem with the image shape of the input model

RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[8, 1, 864, 1251] to have 3 channels, but 
got 1 channels instead

**Comment by yoyomimi** [comment]
Because the evaluation code is currently working for a non-distributed environment. If you want to solve this, you can compare and refer to the train code to add the distribution-related code for evaluation.

**Comment by hutao568** [comment]
I commented out the test code, but it still reports an error. In addition, I use the checkpoint and code you provided, the result file is empty, and the mAP is 0

**Comment by yoyomimi** [comment]
> I commented out the test code, but it still reports an error. In addition, I use the checkpoint and code you provided, the result file is empty, and the mAP is 0

I will update the test code for distributed GPU these days. And for the empty test result, please check the log to make sure you have loaded the checkpoint successfully. If the results are still empty, please let me know. Thanks.

**Comment by hutao568** [comment]
I use the test code to get the following results
![image](https://user-images.githubusercontent.com/17766186/114646427-caf32480-9d0d-11eb-9959-64464311bb3c.png)
The contents of the pred.json file are as follows
![image](https://user-images.githubusercontent.com/17766186/114646460-de9e8b00-9d0d-11eb-8592-4238149cc7f5.png)
The md5 of the ASNet_hoia_resnet50.pth file is 5b0c2ed4f64462c0e0854e31af224ab6

**Comment by yoyomimi** [comment]
Please show the generated .log file to me and I will check that for you.

**Comment by hutao568** [comment]
I checked the log file and it did not succeed in loading the model. ==> model pretrained from {resume_path}', I will try again

**Comment by hutao568** [comment]
Thank you for your patient guidance, I got the same result as in the paper.
![image](https://user-images.githubusercontent.com/17766186/114648639-c4ff4280-9d11-11eb-9acd-3bbfc6c65931.png)
